import { InstanceBase, Regex, InstanceStatus } from "@companion-module/base";
import { UpgradeScripts } from "./upgrades.js";
import UpdateActions from "./actions.js";
import UpdateFeedbacks from "./feedbacks.js";
import UpdateVariableDefinitions from "./variables.js";
import UpdatePresets from "./presets.js";
import { socket } from "./api.js";

/** Companion variable ids allow only [a-zA-Z0-9_]. Screen and cue ids are
 *  generated by caspar-avd and free-form. */
export function safeId(id) {
  return String(id).replace(/[^a-zA-Z0-9_]/g, "_");
}

export default class ModuleInstance extends InstanceBase {
  constructor(internal) {
    super(internal);
    this.snapshot = null;
    this.lastShape = "";
  }

  async init(config) {
    this.config = config;
    this.updateStatus(InstanceStatus.Connecting);
    this.rebuild();
    socket.connect(this);
  }

  async destroy() {
    socket.close();
  }

  async configUpdated(config) {
    this.config = config;
    socket.close();
    this.snapshot = null;
    this.lastShape = "";
    this.updateStatus(InstanceStatus.Connecting);
    socket.connect(this);
  }

  getConfigFields() {
    return [
      {
        type: "static-text",
        id: "info",
        width: 12,
        label: "Connection",
        value:
          "The caspar-avd daemon (not CasparCG itself — the daemon talks AMCP on its behalf). Point this at the address serving the console.",
      },
      {
        type: "textinput",
        id: "host",
        label: "caspar-avd host",
        width: 8,
        default: "127.0.0.1",
        regex: Regex.HOSTNAME,
      },
      {
        type: "textinput",
        id: "port",
        label: "Port",
        width: 4,
        default: "8080",
        regex: Regex.PORT,
      },
    ];
  }

  /**
   * One pushed snapshot.
   *
   * Re-registration is driven by a shape key covering only what the definition
   * sets are built from — screens, cues, pads, media and templates. The
   * snapshot also carries live channel telemetry that changes every frame and a
   * rolling command log, so whole-snapshot comparison would rebuild every
   * dropdown five times a second.
   */
  applySnapshot(snapshot) {
    this.snapshot = snapshot;
    this.updateStatus(InstanceStatus.Ok);

    const show = snapshot?.show ?? {};
    const shape = JSON.stringify([
      (show.screens ?? []).map((s) => [s.id, s.name]),
      (show.cues ?? []).map((c) => [c.id, c.name]),
      (show.pads ?? []).map((p) => [p.index, p.cue]),
      (snapshot?.media ?? []).map((m) => m.id ?? m.name),
      (snapshot?.templates ?? []).map((t) => t.id ?? t.name),
    ]);
    if (shape !== this.lastShape) {
      this.lastShape = shape;
      this.rebuild();
    } else {
      this.refreshVariableValues();
      this.checkAllFeedbacks();
    }
  }

  rebuild() {
    UpdateActions(this);
    UpdateFeedbacks(this);
    UpdateVariableDefinitions(this);
    UpdatePresets(this);
    this.refreshVariableValues();
    this.checkAllFeedbacks();
  }

  show() {
    return this.snapshot?.show ?? {};
  }

  screens() {
    return this.show().screens ?? [];
  }

  cues() {
    return this.show().cues ?? [];
  }

  pads() {
    return this.show().pads ?? [];
  }

  screen(id) {
    return this.screens().find((s) => s.id === String(id ?? "")) ?? null;
  }

  /**
   * What CasparCG says is on a screen's channel/layer, from the OSC telemetry.
   *
   * The show is INTENT; this is live state, and caspar-avd never merges them —
   * a disagreement is information, not a bug. So this reads the telemetry tree
   * rather than the screen's own configuration, and returns null when telemetry
   * is absent entirely (which is different from "nothing is playing").
   */
  layerState(screenId) {
    const s = this.screen(screenId);
    if (!s) return null;
    const channel = (this.snapshot?.channels ?? []).find(
      (c) => Number(c.index ?? c.channel) === Number(s.channel),
    );
    if (!channel) return null;
    const layers = channel.layers ?? channel.stage?.layers ?? {};
    const layer = Array.isArray(layers)
      ? layers.find((l) => Number(l.index ?? l.layer) === Number(s.layer))
      : layers[String(s.layer)];
    return layer ?? null;
  }

  /** True only when telemetry has actually arrived. CasparCG answers no "what
   *  is playing" question over AMCP — it pushes OSC — so no channels means the
   *  module knows nothing, not that nothing is playing. */
  hasTelemetry() {
    return (this.snapshot?.channels ?? []).length > 0;
  }

  refreshVariableValues() {
    const snap = this.snapshot;
    const values = {
      connection_status:
        socket.ws?.readyState === 1 ? "Connected" : "Disconnected",
      casparcg_health: snap?.health ?? "unknown",
      scanner_up: snap?.scanner_up ? "Up" : "Down",
      telemetry: this.hasTelemetry() ? "Receiving" : "None",
      server_version: snap?.server?.version ?? "",
      warning_count: (snap?.warnings ?? []).length,
      media_count: (snap?.media ?? []).length,
      template_count: (snap?.templates ?? []).length,
      cue_count: this.cues().length,
      screen_count: this.screens().length,
    };
    for (const screen of this.screens()) {
      const p = `screen_${safeId(screen.id)}_`;
      const layer = this.layerState(screen.id);
      const fg = layer?.foreground ?? {};
      values[`${p}name`] = screen.name ?? screen.id;
      values[`${p}channel`] = `${screen.channel}-${screen.layer}`;
      values[`${p}enabled`] = screen.enabled ? "Enabled" : "Disabled";
      values[`${p}opacity`] = screen.opacity ?? 1;
      values[`${p}producer`] = fg.producer ?? "";
      values[`${p}file`] = fg.file?.name ?? "";
      // file/time is [position, duration] in SECONDS. There is no frame number
      // on the producer side — derive it as time x fps if you need one.
      values[`${p}position`] = Number(fg.file?.time?.[0] ?? 0).toFixed(2);
      values[`${p}duration`] = Number(fg.file?.time?.[1] ?? 0).toFixed(2);
      values[`${p}paused`] = fg.paused ? "Paused" : "Playing";
    }
    this.setVariableValues(values);
  }
}

export { UpgradeScripts };
